EWPP-4205: Support for operators conditions groups in the mock.
openeuropa/oe_search pull request #110
Opened 2024-03-27 17:12 UTC by hernani

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-04-09 08:19 UTC, upchuk requested changes

2024-04-09 08:19 UTC, upchuk commented on modules/oe_search_mock/src/EuropaSearchMockTrait.php
> +   * Adds values to filters.
This does way more than just "adds values". Add please a description here to understand what happens in the else. Also, no need for else, you can return early.

2024-04-15 12:36 UTC, upchuk approved these changes

2024-04-15 12:37 UTC, 22Alexandra approved these changes
blind for @sergepavle

2024-04-15 12:38 UTC, merged