OEL-101: Europa Search Backend
openeuropa/oe_search pull request #30
Opened 2021-05-05 15:41 UTC by saidatom

## OEL-101

### Description

Add a class EuropaSearchBackend extending Drupal\search_api\Backend\BackendPluginBase and implementing Drupal\Core\Plugin\PluginFormInterface

### Change log

- Added: EuropaSearchBackend with viewSettings, getSupportedFeatures, indexItems, deleteItems, deleteAllIndexItems, search, buildConfigurationForm
- Changed: N/A
- Deprecated: N/A
- Removed: N/A
- Fixed: N/A
- Security: N/A

### Commands

2021-05-06 07:06 UTC, drishu requested changes

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> + * European Commission Europa Search backend for search_api.
```suggestion
 * Europa Search backend for search_api.
```

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +   * The UserPlaces Helper custom module.
Europa Search Service instance
or something of sorts

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +
lets add also 'token_api_endpoint' (available in develop branch)

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +  }
make sure the endpoints are actual urls

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +      ->set('search_api_endpoint', $form_state->getValue('search_api_endpoint'))
also token_api_endpoint, same comment also for other references below

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +    // @todo Support multiple indexes by generating a reference id that takes
If we dont do it now, let's create a follow up ticket and mark it here

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +    $result_set->setResultCount($results);
the result count argument needs to be an int

2021-05-06 07:06 UTC, drishu commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +      $result_set->addResultItem($result_item);
Fields need to be extracted

2021-05-06 09:01 UTC, saidatom commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +    // @todo Support multiple indexes by generating a reference id that takes
follow up ticket OEL-149

2021-05-07 13:11 UTC, saidatom commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +  }
remove this from new version

2021-05-07 13:11 UTC, saidatom commented on src/Plugin/search_api/backend/EuropaSearchBackend.php
> +    $result_set->setResultCount($results);
implemented $search->getTotalResults() in new file

2021-06-09 15:42 UTC, closed without merging