EWPP-1687: Allow to ingest files.
openeuropa/oe_search pull request #56
Opened 2022-01-05 22:17 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-01-11 12:42 UTC, mferran-europe requested changes

2022-01-11 12:42 UTC, mferran-europe commented on src/EventSubscriber/DocumentCreationSubscriber.php
> +    $file = $entity;
$entity could be named directly as $file?

2022-01-11 12:42 UTC, mferran-europe commented on src/EventSubscriber/DocumentCreationSubscriber.php
> +      $fid = $entity->getSource()->getSourceFieldValue($entity);
Might worth checking $fid for a valid value.

2022-01-11 12:42 UTC, mferran-europe commented on src/EventSubscriber/DocumentCreationSubscriber.php
> +      $file = $this->entityTypeManager->getStorage('file')->load($fid) ?? $file;
Same as previous line, here it might also worth checking $file for a valid value.

2022-01-11 12:42 UTC, mferran-europe commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
>          if ($result->getReference()) {
Previous swicth block does not ensure $result contains a valid value.

2022-01-11 12:42 UTC, mferran-europe commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +        switch (1) {
If the functions checked return boolean, it might be clearer using IF/ELSE block.

2022-01-24 15:59 UTC, hernani requested changes

2022-01-24 15:59 UTC, hernani commented on tests/src/Kernel/BackendTest.php
> +   * Test Ingestion.
File ingestion

2022-01-24 15:59 UTC, hernani commented on tests/src/Kernel/BackendTest.php
> +   * Assert data for one ingested file item.
an ingested file item.

2022-01-24 15:59 UTC, hernani commented on tests/src/Kernel/BackendTest.php
> +    // Compare sent data with received data.
Compare the sent files.

2022-03-17 22:36 UTC, hernani approved these changes

2022-03-18 09:31 UTC, 22Alexandra approved these changes

2022-03-18 09:44 UTC, merged