EWPP-2630: Search support for europa search api backend
openeuropa/oe_search pull request #77
Opened 2022-09-27 15:26 UTC by hernani

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-11-14 07:58 UTC, upchuk requested changes

2022-11-14 07:58 UTC, upchuk commented on modules/oe_search_mock/src/EuropaSearchFixturesGenerator.php
> +  protected static function buildScenario(string $scenario_id, array $filters, string $entity_type, $bundle = ''): string {
string $bundle

2022-11-14 07:58 UTC, upchuk commented on modules/oe_search_mock/src/EuropaSearchFixturesGenerator.php
> +      // $entity->metadata += $extra_metadata;
?

2022-11-14 07:58 UTC, upchuk commented on modules/oe_search_mock/src/Plugin/ServiceMock/EuropaSearchServer.php
> +  protected EntityTypeBundleInfoInterface $entityTypeBundleInfo;
no need for the typehinting

2022-11-14 07:58 UTC, upchuk commented on src/EntityMapper.php
> +      $event = new MetadataMappingEvent($query, $metadata, $metadata_key, $field, $entity_values);
This event seems to be dispatched for all fields in index that have a corresponding Druapl field, which are a lot . So if we build a list of 10 nodes, this runs 10xNumber of index fields. Can't we do this alteration after the foreach? I see you are passing anyway all the metadata, entity values (that keep getting populated with each loop)?

This means also updating the event and the subscriber you have.

Also, you are missing the event name.

2022-11-14 07:58 UTC, upchuk commented on src/Plugin/facets/query_type/EuropaSearchApiString.php
> + * We extend the original query type to have better support for booleans.
Let's add another line as to why we are adding better support for booleans in a string plugin :)

2022-11-14 07:58 UTC, upchuk commented on src/Plugin/facets/query_type/EuropaSearchApiString.php
> +      if (count($active_items)) {
This entire block looks very complicated, can you maybe explain it a bit with comments and simplify its reading as much as possible?

2022-11-14 07:58 UTC, upchuk commented on src/Plugin/facets/query_type/EuropaSearchApiString.php
> +    if (!empty($this->results)) {
This is a lot of chunky code, lets add some comments...all sorts of substr that are not easy to understand why.

2022-11-14 08:34 UTC, upchuk requested changes

2022-11-14 08:34 UTC, upchuk commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +    if (!empty($query->getOptions()['offset']) && !empty($query->getOptions()['limit'])) {
You need to also add the limit to the query. By default, it seams ES defaults to 10 but if we need 20, we need to send the limit. This also means that you need to update the `getFiltersFromRequest()` to add the page size. However, in order to avoid having to re-generate all our md5 scenario IDs, you can add the limit only if it's not the default 10. SOmething like this:

```
    if (isset($url_query_parameters['pageSize']) && $url_query_parameters['pageSize'] !== "10") {
      $filters['page_size'] = $url_query_parameters['pageSize'];
    }
```

2022-11-14 12:14 UTC, upchuk requested changes

2022-11-14 12:14 UTC, upchuk commented on src/EntityMapper.php
> +      $this->eventService->dispatch($event);
Where is the event name? It's not a valid event dispatching.

Also, let's name the variable `eventDispatcher` isntead of event service.

2022-11-15 13:31 UTC, upchuk requested changes
Missing tests for the limit.

2022-11-15 19:00 UTC, sergepavle commented on oe_search.module
> +  foreach ($servers as $server) {
```suggestion
  $europa_servers = [];
  foreach ($servers as $server) {
```

2022-11-15 19:00 UTC, sergepavle commented on oe_search.module
> +        ':input[name="server"]' => _oe_search_get_europa_servers(),
It doesn't work properly if we don't have available ES servers.

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +  public function __construct(array $configuration, $plugin_id, array $plugin_definition, HttpClientInterface $http_client, Settings $settings, ContainerAwareEventDispatcher $event_service, QueryExpr
```suggestion
  public function __construct(array $configuration, $plugin_id, array $plugin_definition, HttpClientInterface $http_client, Settings $settings, EventDispatcherInterface $event_dispatcher, QueryExpressionBuilder $query_expression_builder, EntityMapper $entity_mapper) {
```

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      $result = $this->getClient()->search(NULL, NULL, ['bool' => ['must' => ['term' => ['SEARCH_API_SITE_HASH' => Utility::getSiteHash()]]]], NULL, NULL, $page++);
Why structure of the query is changed? Is it about a change in the API of ES?

2022-11-15 19:00 UTC, sergepavle commented on tests/src/FunctionalJavascript/BackendUiTest.php
> +    $this->drupalGet('admin/config/search/search-api/add-index');
I think we need to cover cases when we don't have ES type server available (to make sure that #states work properly).

2022-11-15 19:00 UTC, sergepavle commented on tests/src/Kernel/BackendIngestionTest.php
> +    for ($i = 1; $i <= 5; $i++) {
Probably it should be 15 items. But looks like there are discrepancies in the number of items.
```suggestion
    for ($i = 1; $i <= 15; $i++) {
```

2022-11-15 19:00 UTC, sergepavle commented on tests/src/Kernel/BackendSearchTest.php
> +    $this->assertEquals('entity:entity_test_mulrev_changed/2:en', $first_result->getId());
We may assert both item ids.

2022-11-15 19:00 UTC, sergepavle commented on src/QueryExpressionBuilder.php
> +    $conditions = $negated_conditions = $return = [];
```suggestion
    $conditions = $negated_conditions = [];
```

2022-11-15 19:00 UTC, sergepavle commented on src/QueryExpressionBuilder.php
> +        if (strpos($tag, 'facet:') === 0) {
Does it mean that if the group contains at least 1 tag with facets, handling conditions should be stopped? I am asking just to confirm.

2022-11-15 19:00 UTC, sergepavle commented on src/QueryExpressionBuilder.php
> +      'bool' => $query_conjunctions,
Probably we have to set a default value for this variable.

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      $limit = $query->getOptions()['limit'];
Are we sure about incoming data? Probably we have to cast that value as an integer.

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      $keys = $query->getKeys();
Are we sure that keys are always is an array?

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      $item_id = ($entity_load_mode == 'local') ? $metadata['SEARCH_API_ID'][0] : $item->getUrl();
```suggestion
      $item_id = ($entity_load_mode === 'local') ? $metadata['SEARCH_API_ID'][0] : $item->getUrl();
```

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      if ($entity_load_mode == 'remote' && $mapped_entity = $this->entityMapper->map($metadata, $query)) {
```suggestion
      if ($entity_load_mode === 'remote' && $mapped_entity = $this->entityMapper->map($metadata, $query)) {
```

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +    // Used for or facets.
```suggestion
    // Used for OR facets.
```

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      if (!$condition instanceof ConditionGroup || $condition->getConjunction() != 'OR') {
```suggestion
      if (!$condition instanceof ConditionGroup || $condition->getConjunction() !== 'OR') {
```

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +  protected function getFacets(QueryInterface $query, array $available_facets = [], string $text = NULL) {
```suggestion
  protected function getFacets(QueryInterface $query, array $available_facets = [], string $text = NULL): array {
```

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/facets/query_type/EuropaDate.php
> + * Extends the original query type to handle date values in miliseconds.
```suggestion
 * Extends the original query type to handle date values in milliseconds.
```

2022-11-15 19:00 UTC, sergepavle commented on src/Plugin/facets/query_type/EuropaSearchApiString.php
> +  public function execute() {
Is it not possible to alter the query after paren execution?

2022-11-16 14:49 UTC, sergepavle commented on src/EventSubscriber/EuropaEntityCreationSubscriber.php
> +   * Constructs a MetadataMappingSubscriber object.
```suggestion
   * Constructs a EuropaEntityCreationSubscriber object.
```

2022-11-16 14:49 UTC, sergepavle commented on src/EventSubscriber/EuropaEntityCreationSubscriber.php
> +    $datasource_id = $metadata[Utility::getEsFieldName('search_api_datasource', $query)][0];
```suggestion
    $datasource_id = $metadata[Utility::getEsFieldName('search_api_datasource', $query)][0];

    $datasource = $event->getQuery()
      ->getIndex()
      ->getDatasource($datasource_id);

```

2022-11-16 14:49 UTC, sergepavle commented on src/EventSubscriber/EuropaEntityCreationSubscriber.php
> +      if ($metadata_key != Utility::getEsFieldName($entity_bundle_key, $query) && in_array($original_field_type, $entity_reference_types)) {
```suggestion
      if ($metadata_key !== Utility::getEsFieldName($entity_bundle_key, $query) && in_array($original_field_type, $entity_reference_types)) {
```

2022-11-16 14:49 UTC, sergepavle commented on src/EventSubscriber/EuropaEntityCreationSubscriber.php
> +      if ($field->getType() == 'boolean') {
```suggestion
      if ($field->getType() === 'boolean') {
```

2022-11-16 14:49 UTC, sergepavle commented on src/EventSubscriber/EuropaEntityCreationSubscriber.php
> +      elseif ($field->getType() == 'date') {
```suggestion
      elseif ($field->getType() === 'date') {
```

2022-11-16 14:49 UTC, sergepavle commented on src/Event/EuropaEntityCreationEvent.php
> +   * The name of the event dispatched when a new europa entity is instatiated.
```suggestion
   * The name of the event dispatched when a new europa entity is instantiated.
```

2022-11-22 16:01 UTC, hernani commented on src/Plugin/facets/query_type/EuropaSearchApiString.php
> +  public function execute() {
I couldn't find a way, and I didn't want to mess with facet active values just for this (and for dates which are done in a similar way).

2022-11-22 16:05 UTC, hernani commented on src/QueryExpressionBuilder.php
> +        if (strpos($tag, 'facet:') === 0) {
Yes this is used for must_not clauses.

2022-11-22 16:05 UTC, hernani commented on tests/src/FunctionalJavascript/BackendUiTest.php
> +    $this->drupalGet('admin/config/search/search-api/add-index');
I have just added a bit above.

2022-11-22 17:03 UTC, hernani commented on tests/src/Kernel/BackendIngestionTest.php
> +    for ($i = 1; $i <= 5; $i++) {
The mock returns the same result for the search test which created 15 items. In this test though we only create 5 items, so we only test those, otherwise it would fail with an invalid scenario.

2022-11-22 17:57 UTC, sergepavle commented on oe_search.module
> +        ],
There are still issue with #states in some cases. Few steps to reproduce:

1. Enable Database search module
2. Create search API server with Database type
3. Create search API server with Europa search
4. Open index creation form
5. Set name of index
6. Select data source (Content)
7. Select in radio button database type server
Europa search index options fieldset appeared but shouldn't be visible yet.

2022-11-22 17:59 UTC, sergepavle commented on oe_search.module
> +        ':input[name="server"]' => _oe_search_get_europa_servers(),
Seems like these changes helped to fix but I don't sure
At least for me, it works.
`Index: oe_search.module
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/oe_search.module b/oe_search.module
--- a/oe_search.module	(revision ee3fe1d5e7ad0425d86401a4e14f6c50b2745917)
+++ b/oe_search.module	(date 1669139444419)
@@ -90,8 +90,6 @@
       'visible' => [
         ':input[name="server"]' => [
           _oe_search_get_europa_servers(),
-          'and',
-          ['filled' => TRUE],
         ],
       ],
     ],
@@ -132,7 +130,7 @@
       'value' => $server->id(),
     ];
   }
-  return $valid_options;
+  return $valid_options ?? FALSE;
 }
 
 /**
`

2022-11-23 15:38 UTC, sergepavle approved these changes, later dismissed

2022-11-28 09:03 UTC, upchuk approved these changes

2022-11-28 09:04 UTC, sergepavle approved these changes

2022-11-28 09:04 UTC, merged