EWPP-2437: Ensure search api backend pages won't crash.
openeuropa/oe_search pull request #78
Opened 2022-10-20 09:54 UTC by nagyad

2022-10-20 09:59 UTC, brummbar requested changes

2022-10-20 09:59 UTC, brummbar commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      // we consider that as not available.
This is not exactly true, we are catching all exceptions so it could be any type of error.

2022-10-20 09:59 UTC, brummbar commented on src/Plugin/search_api/backend/SearchApiEuropaSearchBackend.php
> +      // we consider that as not available.
I would also log the exception here, so that when we have real errors (not caused by a missing development setup) they can be logged.

2022-10-20 10:53 UTC, brummbar requested changes
I didn't test is locally but I approve the approach.

Edit: This was an approval, I misclicked.

2022-10-20 10:54 UTC, brummbar submitted a review, later dismissed

2022-10-25 08:40 UTC, brummbar approved these changes

2022-10-25 10:01 UTC, hernani approved these changes

2022-10-25 10:01 UTC, merged